# Secuboid pipeline configuration
image: maven:3.6.2-jdk-8

clone:
pipelines:
  default:
    - step:
        name: Verify
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn --batch-mode verify
  branches:
    master:
      - step:
          name: Build and deploy
          caches:
            - maven
          script:
            - bash pipelines/configure-maven.sh
            - mvn --batch-mode source:jar javadoc:jar javadoc:javadoc deploy
          artifacts: # defining the artifacts to be passed to each future step.
            - target/**
      - step:
          name: Javadoc deploy
          image: cschlosser/alpine-lftps
          script:
            - sh pipelines/upload-javadoc.sh
      - step:
          name: Set jar available for download
          script:
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$(ls target/*.jar | grep -v ^target/original | grep -v javadoc.jar$ | grep -v sources.jar$)"
