##################################################################
# Secuboid config file                                           #
##################################################################
General:                             # ----General Config----
  Lang: english                      # english, french for now (or your own)
  # "flat" files or "mysql" (included and recommended Maria) are supported.
  # If you want to switch from flat file to MySQL/Maria, just stop the server, change
  # the value to "mysql" and on server restart, Secuboid will convert to MySQL.
  Storage: flat                      # flat or mysql
  MySQL:
    HostName: localhost
    Port: 3306
    Database: secuboid
    User: secuboid
    Password: mypass
    Prefix: secuboid_                # Can be '' if Secuboid uses it own
                                     # database

  # The next value is if you want the Secuboid explosion protection.
  # Set it to "False" if you prefer to disable explosions from Essentials
  # or avoiding plugin conflicts. Flags (???_DAMAGE) will be ignored.
  OverrideExplosions: true

  UseEconomy: false

  # The players can have more than one inventory or a separate
  # creative inventory. Do not activate this option if you have
  # an other inventory plugin (Multiverse Inventories, ,..)
  # If true, see inventory.yml
  MultipleInventories: false # Need restart if changed

  # Activate FLY and CREATIVE permissions. Secuboid will change automatically
  # the game mode where those flags are active/inactive. See below for
  # extra configuration.
  FlyAndCreative: false # Need restart if changed

  # For material list:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  InfoItem: BONE                     # Item that give Land information
  SelectItem: ROTTEN_FLESH           # Item that give Land selection

# Lands configuration
Lands:
  Types:
    List:                            # land types or categories
      - admin
      - player
    OnCreate:                        # Automatic categories on create
      AdminMode: admin               # On admin mode (or "-null-")
      NoneAdminMode: player          # Non admin mode (normal players or "-null-")

  # AllowCollision:
  # true: Collisions are permitted without verification.
  # approve: A player with permission secuboid.approvecollision must approve
  #          the land created if there is a collision.
  # false: No collision permitted.
  AllowCollision: approve            # true, approve, false

  LandChat: true                     # Allow private chat in lands (=, < and >)
  SpectatorIsVanish: true            # true, Spectator players are not shown in 
                                     # land players list
  ApproveNotifyTime: 24002           # Time to notify for Approval (in ticks)
                                     # or 0 for disabling
  SelectAutoCancel: 12000            # Time before auto cancel a selection
                                     # or 0 for disabling
  DefaultXsize: 10                   # Size on selection start
  DefaultZsize: 10
  DefaultBottom: 0                   # Default selection: positive = absolute
  DefaultTop: 255                    # negative = from player feet
  DefaultRadius: 5                   # Default selection radius for roads
  MaxBottom: 0                       # Maximum selection high
  MaxTop: 255
  MaxRadius: 10                      # Maximum selection radius for roads
  # Not selected blocks in road selection
  DefaultNonSelectedMaterials:
    - BEDROCK
    - DIRT
    - END_STONE
    - GRASS
    - ACACIA_LEAVES
    - BIRCH_LEAVES
    - DARK_OAK_LEAVES
    - JUNGLE_LEAVES
    - OAK_LEAVES
    - SPRUCE_LEAVES
    - ACACIA_LOG
    - BIRCH_LOG
    - DARK_OAK_LOG
    - JUNGLE_LOG
    - OAK_LOG
    - SPRUCE_LOG
    - NETHERRACK
    - SAND
    - SOUL_SAND
    - STONE
  MaxLandPerPlayer: 5

  Areas:
    MaxAreaPerLand: 3

  OwnerCanSet:                     # What the owner can set on his land?
    Permissions:
      - BUILD
      - OPEN
      - USE
      - ANIMAL_KILL
      - TAMED_KILL
      - VILLAGER_KILL
      - VILLAGER_GOLEM_KILL
      - HORSE_KILL
    Flags:
      - TNT_EXPLOSION
      - TNT_DAMAGE
      - MESSAGE_ENTER
      - MESSAGE_EXIT

# Fly and Creative configuration (only if general.FlyAndCreative is activated)
FlyCreative:
  # Game Modes to ignore
  IgnoredGameMode:
    - ADVENTURE
    - SPECTATOR

  # Configuration for creative mode only
  Creative:

    # Disallow to drop any item?
    # Override permission: secuboid.flycreative.override.nodrop
    NoDrop: true

    # Disallow to open a chest, furnace, ender chest, ...
    # Override permission: secuboid.flycreative.override.noopenchest
    NoOpenChest: true

    # Disallow to build outside a cuboid if the player is near the border
    # Override permission: secuboid.flycreative.override.nobuildoutside
    NoBuildOutside: true

    # List of banned items in creative mode
    # Override permission: secuboid.flycreative.override.allowbanneditems
    # You have a list of material names here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    BannedItems:
      - EXP_BOTTLE
      - DIAMOND_BLOCK
      - DIAMOND_ORE
      - DIAMOND
      - IRON_BLOCK
      - IRON_ORE
      - IRON_INGOT
      - GOLD_BLOCK
      - GOLD_ORE
      - GOLD_INGOT
      - EMERALD_BLOCK
      - EMERALD_ORE
      - EMERALD
