name: Secuboid
main: me.tabinol.secuboid.Secuboid
version: ${project.version}
description: "Lands and grief protection plugin"
authors: [Tabinol, Kaz00, Ouaou]
depend: [Vault]
softdepend: [WorldEdit, Essentials, VanishNoPacket, SuperVanish, PremiumVanish]
api-version: 1.15
commands:
   secuboid:
      description: Secuboid Command
      aliases: [sd, factoid, fd]
      usage: /secuboid help
      permission: secuboid.use
      permission-message: you don't have permission for that!
permissions:
    secuboid.*:
        description: Secuboid Command Permission
        default: op
        children:
            secuboid.adminmode: true
            secuboid.adminmode.auto: true
            secuboid.collisionapprove: true
            secuboid.socialspy: true
            secuboid.bypassban: true
            secuboid.use: true
            secuboid.reload: true
            secuboid.inv.*: true
            secuboid.flycreative.*: true
    secuboid.adminmode:
        description: Can use Admin Mod
        default: op
    secuboid.adminmode.auto:
        description: Auto Admin Mod on connect
        default: op
        children:
            secuboid.adminmode: true
    secuboid.collisionapprove:
        description: Can approve land creation collisions
        default: op
    secuboid.socialspy:
        description: Can read conversations from all lands
        default: op
    secuboid.bypassban:
        description: Ban and kick does not affect this player
        default: op
    secuboid.use:
        description: Can use secuboid command
        default: op
    secuboid.reload:
        description: Can reload the plugin
        default: op

    # Inventory
    secuboid.inv.*:
        description: All permisions for inventory (except inventory changes)
        default: op
        children:
            secuboid.inv.forcesave: true
            secuboid.inv.default: true
            secuboid.inv.loaddeath: true
            secuboid.inv.ignoredisabledcommands: true
    secuboid.inv.forcesave:
        description: Can use /secuboid finv forcesave command
        default: op
    secuboid.inv.default:
        description: Can use /secuboid finv default command
        default: op
    secuboid.inv.loaddeath:
        description: Can use /secuboid finv loaddeath command
        default: op
    secuboid.inv.ignorecreativeinv:
        description: Ignore creative inventory change
        default: false
    secuboid.inv.ignoreinv:
        description: Ignore inventory change
        default: false
        children:
            secuboid.inv.ignorecreativeinv: true
    secuboid.inv.ignoredisabledcommands:
        description: Ignore disabled commands
        default: op

    # FlyCreative
    secuboid.flycreative.*:
        description: Gives access to all flyncrative permissions
        default: op
        children:
            secuboid.flycreative.ignorefly: true
            secuboid.flycreative.ignorecreative: true
            secuboid.flycreative.override.*: true
    secuboid.flycreative.override.*:
        description: Gives access to all override permissions
        default: op
        children:
            secuboid.flycreative.override.nodrop: true
            secuboid.flycreative.override.noopenchest: true
            secuboid.flycreative.override.nobuildoutside: true
            secuboid.flycreative.override.allowbanneditems: true
    secuboid.flycreative.ignorefly:
        description: Ignore fly change in cuboid
        default: op
    secuboid.flycreative.ignorecreative:
        description: Ignore creative mode change in cuboid
        default: op
        children:
            secuboid.flycreative.override.nodrop: true
            secuboid.flycreative.override.noopenchest: true
            secuboid.flycreative.override.nobuildoutside: true
            secuboid.flycreative.override.allowbanneditems: true
    secuboid.flycreative.override.nodrop:
        description: Can drop items in creative
        default: op
    secuboid.flycreative.override.noopenchest:
        description: Can open chests in creative
        default: op
    secuboid.flycreative.override.nobuildoutside:
        description: Can build outside the zone in creative
        default: op
    secuboid.flycreative.override.allowbanneditems:
        description: Can have banned items in creative
        default: op

