# Configuration for worlds
# Important: For Permission keys, replace "." by "_".
# Example: "group.newbies" will become "group_newbies"

_Global_:                           # _Global_ is for all worlds
  ContainerPermissions:
    Group:
      newbies:
        BUILD:
          Value: false
          Inheritable: true
        OPEN:
          Value: false
          Inheritable: true
        BUCKET_WATER:
          Value: false
          Inheritable: true
        BUCKET_LAVA:
          Value: false
          Inheritable: true
      users:
        LAND_CREATE:
          Value: true
          Inheritable: false
        BUILD:
          Value: true
          Inheritable: false
        ECO_LAND_FOR_SALE:
          Value: true
          Inheritable: true
        ECO_LAND_BUY:
          Value: true
          Inheritable: true
        ECO_LAND_FOR_RENT:
          Value: true
          Inheritable: true
        ECO_LAND_RENT:
          Value: true
          Inheritable: true
  ContainerFlags:
    FIRESPREAD:
      Value: true
      Inheritable: true
    CREEPER_DAMAGE:
      Value: true
      Inheritable: true
    TNT_EXPLOSION:
      Value: true
      Inheritable: true
    TNT_DAMAGE:
      Value: true
      Inheritable: true
    ENDERMAN_DAMAGE:
      Value: true
      Inheritable: true
    WITHER_DAMAGE:
      Value: true
      Inheritable: true
    ENDERDRAGON_DAMAGE:
      Value: true
      Inheritable: true
    GHAST_DAMAGE:
      Value: true
      Inheritable: true
    FULL_PVP:
      Value: true
      Inheritable: true
    ECO_BLOCK_PRICE:
      Value: 0.01
      Inheritable: true
#world1:
#  ContainerPermissions:
#    Group:
#      newbies:
#        BUILD_PLACE:
#          Value: false
#          Inheritable: true
#        BUILD_DESTROY:
#          Value: false
#          Inheritable: true
#    everybody:
#      BUILD_PLACE:
#        Value: true
#        Inheritable: false
#      BUILD_DESTROY:
#        Value: true
#        Inheritable: false
#  ContainerFlags:
#    CREEPER_DAMAGE:
#      Value: true
#      Inheritable: false
