# Flags and permissions for worlds

# Permissions section
# ===================
# playercontainers (list)      : List the players/groups who need the
#                                permission
#   Everybody: Everybody
#   Owner    : The land owner
#   Resident : The land resident
#   Tenant   : The land tenant
#   g:mygroup: Permission system group
#   b:my.perm: Players who have the Bukkit permission
# permissions (list)           : A Land permission list (See the wiki)
# value (bool)                 : true or false
# inheritable (bool, optional) : If the value is inheritable (default true)
# world (string, optional)     : List of affected worlds (default all)
permissions:

  # Every worlds
  - playercontainers: g:newbies
    permissions: 
      - BUILD
      - OPEN
      - TRADE
      - BUCKET_WATER
      - BUCKET_LAVA
      - USE_REPEATER
      - USE_COMPARATOR
      - USE_NOTEBLOCK
      - TAME
    value: false
  - playercontainers: g:regular
    permissions: BUILD
    value: true
    inheritable: false

  # Survival world
  - playercontainers: Everybody
    permissions: 
      - EAT_CHORUS_FRUIT
      - USE_MOBSPAWNER
    value: false
    worlds: world
  - playercontainers: g:newbies
    permissions:
      - BUILD
      - TRADE
      - BUCKET_WATER
      - BUCKET_LAVA
      - ECO_LAND_FOR_SALE
      - ECO_LAND_BUY
      - ECO_LAND_FOR_RENT
      - ECO_LAND_RENT
    value: true
    worlds: world
  - playercontainers: g:regular
    permissions: LAND_CREATE
    value: true
    inheritable: false
    worlds: world

#  # The end
#  - playercontainers: g:newbies
#    permissions: BUILD
#    value: false
#    inheritable: false
#    worlds: world_the_end

#  # Creative
#  - playercontainers: Everybody
#    permissions: CREATIVE
#    value: true
#    worlds: creative_world

# Flags section
# =============
# flags (list)                 : A Land permission list (See the wiki)
# value (bool, str, list, num) : See the wiki for available values
# inheritable (bool, optional) : If the value is inheritable (default true)
# world (string, optional)     : List of affected worlds (default all)
flags:
  
  # Every worlds
  - flags:
      - CREEPER_DAMAGE
      - TNT_DAMAGE
      - END_CRYSTAL_DAMAGE
      - FIREWORK_DAMAGE
      - FIRESPREAD
      - ENDERMAN_DAMAGE
      - WITHER_DAMAGE
      - GHAST_DAMAGE
      - ENDERDRAGON_DAMAGE
      - FULL_PVP
    value: false
  - flags: ECO_BLOCK_PRICE
    value: 1.00

#  # Creative
#  - flags: INVENTORY
#    value: creative
#    worlds: creative_world
#  - flags: LEAF_DECAY
#    value: false
#    worlds: creative_world
