version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    working_directory: ~/secuboid-minecraft-plugin
    docker:
      - image: circleci/openjdk:16-jdk-buster
    steps:
      - checkout
      - restore_cache:
          key: secuboid-minecraft-plugin-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: secuboid-minecraft-plugin-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - run:
          name: Creating Artifacts
          command: |
            mkdir /tmp/artifacts;
            cp target/secuboid-*.jar /tmp/artifacts/;
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - secuboid-*.jar
      - discord/status
  deploy:
    docker:
      - image: circleci/ubuntu-server
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^master$|^\d+\.\d+\.\d+$/